### ISSUE TITLE
account.unlockViaArkoseCaptcha()

### ISSUE THREAD

**Issue by codilau** [obnoxiousish/async_twitter_api_client#2]
Hi, thanks for this great tool. It looks very promising.
I was interested in the account.unlockViaArkoseCaptcha() function but can't make it work and I;m not sure where I'm screwing it up.
Would you mind sharing a usage example? I've got a API key for twocaptcha

**Comment by obnoxiousish** [comment]
are you calling asyncAuthenticate first? this function does not require any arguments

**Comment by obnoxiousish** [comment]
also make sure you add debug=True to the init

**Comment by obnoxiousish** [comment]
as well the twocaptcha key is provided at init and not when the function is called

**Comment by obnoxiousish** [comment]
today i will add some documentation to init and unlock and authenticate and give real var names and type hints instead of args kwargs

**Comment by codilau** [comment]
I'm instantianting as in your example passing the twocaptchaapikey as kwarg then
I'm calling asyncAuthenticate, passing cookies as kwargs.
Then I tried a few things around await twitter.unlockvia... with no arguments

**Comment by obnoxiousish** [comment]
the example provided in testAsyncTwitter.py is what works for me on many accounts, so if its not working for you i have no idea why sir i apologize, note that sometimes twocaptcha provides invalid captchas or provides no captcha at all and can take 3+ tries for a single unlock

**Comment by obnoxiousish** [comment]
Another issue might be that it submits lang: en, if account isnt english maybe a problem

**Comment by obnoxiousish** [comment]
I just pushed an update that upgrades a lot, try now

**Comment by obnoxiousish** [comment]
Also realized was a problem with the debug logger i fixed

**Comment by obnoxiousish** [comment]
Fixed another issue with the unlocker, wasnt working in last update should work now

**Comment by obnoxiousish** [comment]
![asyncAccount py_-_async-twitter-api-client_-_Visua_2024_04_28_14_32_14](https://github.com/obnoxiousish/async_twitter_api_client/assets/18523901/704971de-ecac-4913-82d4-c57e3035d42e)

Going to consider the issue closed perhaps unless more information is provided, refer to testAsyncTwitter.py

**Comment by obnoxiousish** [comment]
hmm seems there is still something wrong with the headers after a bunch of updates, gonna look into it more when i can

**Comment by obnoxiousish** [comment]
I think i finally found the issue, i think it was related to it accidentally sending the wrong cookies due to it having a cookie header from copying the headers and having cookies from copying cookies, also decided to copy the headers more.

I think it should properly support accoutns with other languages now as well, cleared a lock on a pt and a en account.

Please let me know if there is still an issue, will close in a few days if no reply

**Comment by obnoxiousish** [comment]
More updates added, it's very reliable now I find

**Comment by codilau** [comment]
Brilliant mate! Awesome work and thanks a lot for the effort.
It now works as expected. I'll keep using and exposing other bugs I might find!

**Comment by obnoxiousish** [comment]
There are quite a few things needed to be done, there are various discrepancies in asyncAccount & scraper & search because Trevor decided to have them use a different login() for each file, unifiying these functions into one location and unifiying the logger functions would be something important to do

Also missing tons of documentation, has awful variable names in some places as well.

Theres also some other stuff in the TODO in README.md, considering forking and contributing<3
